server:
  port:
    8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/websiteroomforrent
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: khibach2004@gmail.com
    password: cfdo lgkl lcxv fmkj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

api:
  prefix: api

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: XF/TkGiBVFRoSUxPSIJ6zjS/mk53nDENCgG4NWwMgbg=