server:
  port:
    8080
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: daoquocbao2k04@gmail.com
    password: fydz hfxc bgvn ndri
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:mysql://localhost:3306/websiteroomforrent
    username: root
    password: Baomax1001.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
api:
  prefix: api
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: XF/TkGiBVFRoSUxPSIJ6zjS/mk53nDENCgG4NWwMgbg=