server:
  port: 8080

spring:
  profiles:
    active: default
  mail:
    host: smtp.gmail.com
    port: 587
    username: daoquocbao2k04@gmail.com
    password: fydz hfxc bgvn ndri
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/websiteroomforrent}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
api:
  prefix: api

jwt:
  expiration: 2592000 # 30 days = 30 * 24 * 60 * 60
  secretKey: XF/TkGiBVFRoSUxPSIJ6zjS/mk53nDENCgG4NWwMgbg=